### ISSUE TITLE
Unpredictable unfolding

### ISSUE THREAD

**Issue by modulovalue** [andrasferenczi/dart-data-plugin#1]
Thank you for the _godly_ plugin!

I'd like to ask you, if you could make the following change to the folding comment
[auto fold](https://intellij-support.jetbrains.com/hc/en-us/community/posts/206315019-Comment-to-auto-fold-a-region-of-code-)

The folded data part just unfolds itself in an unpredictable way. `defaultstate="collapsed"` seems to fix it.

```
changing
`//<editor-fold desc="Data Methods">`
to
`//<editor-fold desc="Data Methods" defaultstate="collapsed">`
```
Thanks!

**Comment by andrasferenczi** [comment]
@modulovalue 

I don't see any difference with the `editor-fold` comment  you propose. Any file that was once opened will remember it's folded state as discussed in the linked bugtracker [here](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000331824-Automatic-folding-not-working).

Nevertheless, I [added this small change](https://github.com/andrasferenczi/dart-data-plugin/commit/79f7817eb65025fe55763019485c0b1f118dcd7c) and the new version is waiting for approval by Jetbrains.
