### ISSUE TITLE
Misleading copyWith behaviour

### ISSUE THREAD

**Issue by vasiliyMiroshnichenko** [andrasferenczi/dart-data-plugin#10]
The "copyWith" method should not have identical(...) optimization. Since it changes method behavior and can lead to errors.

For example, if I have a mutable class, I can protect myself from side effects by just copying this object without changing it.

With this optimization, the method doesn't do what should do. It says that it copying objects. And I, as a developer, expect just only it.

**Comment by andrasferenczi** [comment]
The general idea with the `data` classes is that they should be immutable, so I guess that is why I left the corresponding setting enabled by default.

You can change this optimization by changing the appropriate toggle in `Settings`. 

You can reopen this issue if you still have issues with this.
