### ISSUE TITLE
Maintainers needed

### ISSUE THREAD

**Issue by andrasferenczi** [andrasferenczi/dart-data-plugin#17]
I thought I'd need to write a couple words, because this repository hasn't been updated for a while.

First off, I am pleasantly surprised that there are people commenting and voting here about issues with the plugin, I didn't imagine that many people are going to use it. I am glad so many of you developers are using it.

Unfortunately, even though Dart has improved, I haven't added anything to this codebase in the last year or so and I think this plugin should be kept up-to-date, because there are many people using it.

I have been thinking (and hesitating a lot - hence the code deletion) what I should do with this plugin and I've evaluated that I don't have any interest in developing this plugin further (definitely not in a year's time). I have moved away from Dart and Flutter, I am not developing in them anymore. Jetbrains plugins are also niche products and I don't think my developer time is invested well working on this project. Not to mention the fact that this plugin gives me no income at all, it is all free.

So I am giving it away to the community. I've committed the source code to this repository.

What I am not planning to do:
- implement new features / changes
- setup the project on my machine
- do manual tests to see if the code works

The support I can provide:
- provide code reviews
- give others rights in this repo as needed
- enable others to setup CI / implement new features

Feel free to add your thoughts here and get the discussion started.

**Comment by deviankim** [comment]
I updated the PR conflict resolved.

Can you review this?

https://github.com/andrasferenczi/dart-data-plugin/pull/15
