### ISSUE TITLE
new keyword at copy

### ISSUE THREAD

**Issue by matejwamf** [andrasferenczi/dart-data-plugin#2]
Hello,

can we remove new keyword at copy function?

Love the plugin btw

Instead of 
```
Something copyWith({
  }) {
    return new Something(
    );
  }
```
Make
```
Something copyWith({
  }) {
    return Something(
    );
  }
```

**Comment by andrasferenczi** [comment]
Unchecking the checkbox at `Settings` > `Editor` > `Dart Data Class Plugin` > `use the 'new' keyword` should do the trick.

Let me know if you still need help.

**Comment by matejwamf** [comment]
Thank you. I missed that one.

<3
