### ISSUE TITLE
Generated `Named Argument Constructor` alway insert in the end of the class.

### ISSUE THREAD

**Issue by huhuang03** [andrasferenczi/dart-data-plugin#5]
Like the title describe, but I want the generated code insert at the cursor position. How can I do this?

**Comment by andrasferenczi** [comment]
I don't think it's currently supported. If I remember correctly, the generated code is always placed at the same location, to be able to override the old code with the new one.

**Comment by andrasferenczi** [comment]
Version `0.1.0` should fix this issue, which will be available in a couple days after Jetbrains' approval. Please reopen this ticket if you still have this issue after that.
