### ISSUE TITLE
Update to new dart version syntax and effective dart lint suggestions

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [andrasferenczi/dart-data-plugin#6]
Strings need to be interpolated.
Current style:   
```dart
return 'Tag{' + ' name: $name,' + ' options: $options,' + '}';
```
suggested
 
```dart
return 'Tag{name: $name, options: $options}';
```

Remove new from generated code

**Comment by andrasferenczi** [comment]
Version `0.1.0` should fix this issue, which will be available in a couple days after Jetbrains' approval. Please reopen this ticket if you still have this issue after that.
