### ISSUE TITLE
whether the constructor can generate optional parameters

### ISSUE THREAD

**Issue by lihaotian0607** [andrasferenczi/dart-data-plugin#8]
```dart
class ClassName {
   final String field;
 
// no need for @required
ClassName({this.field});
}

**Comment by andrasferenczi** [comment]
`@required` can be disabled in general in the settings menu.

There is no way to specify how to generate for SOME fields only. If you have a suggestion for this case, pls share.

Did that answer your question?

**Comment by lihaotian0607** [comment]
ok, thanks😬
